# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\USER\PycharmProjects\workdays\tab_for_tabel_dial.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(472, 402)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dateEdit_from = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_from.setGeometry(QtCore.QRect(190, 49, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit_from.setFont(font)
        self.dateEdit_from.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dateEdit_from.setCalendarPopup(True)
        self.dateEdit_from.setObjectName("dateEdit_from")
        self.dateEdit_to = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_to.setGeometry(QtCore.QRect(340, 49, 110, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit_to.setFont(font)
        self.dateEdit_to.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dateEdit_to.setCalendarPopup(True)
        self.dateEdit_to.setObjectName("dateEdit_to")
        self.pushButton_workday = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_workday.setGeometry(QtCore.QRect(20, 19, 141, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_workday.setFont(font)
        self.pushButton_workday.setObjectName("pushButton_workday")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 59, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 59, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listWidget_holidays = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_holidays.setGeometry(QtCore.QRect(20, 120, 291, 211))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listWidget_holidays.setFont(font)
        self.listWidget_holidays.setObjectName("listWidget_holidays")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(330, 119, 121, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dateEdit_holidays = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit_holidays.setFont(font)
        self.dateEdit_holidays.setCalendarPopup(True)
        self.dateEdit_holidays.setObjectName("dateEdit_holidays")
        self.verticalLayout.addWidget(self.dateEdit_holidays)
        self.pushButton_add_holiday = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_add_holiday.setFont(font)
        self.pushButton_add_holiday.setObjectName("pushButton_add_holiday")
        self.verticalLayout.addWidget(self.pushButton_add_holiday)
        self.pushButton_remove_holiday = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_remove_holiday.setFont(font)
        self.pushButton_remove_holiday.setObjectName("pushButton_remove_holiday")
        self.verticalLayout.addWidget(self.pushButton_remove_holiday)
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(30, 340, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_info.setFont(font)
        self.label_info.setObjectName("label_info")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 472, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Рабочие дни"))
        self.pushButton_workday.setText(_translate("MainWindow", "Выбрать период\n"
"и создать\n"
"таблицу "))
        self.label.setText(_translate("MainWindow", "С:"))
        self.label_2.setText(_translate("MainWindow", "ПО:"))
        self.dateEdit_holidays.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.pushButton_add_holiday.setText(_translate("MainWindow", "Добавить\n"
"праздник"))
        self.pushButton_remove_holiday.setText(_translate("MainWindow", "Удалить\n"
"праздник"))
        self.label_info.setText(_translate("MainWindow", "INFO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
